language: node_js
node_js:
 - "node"
services:
  - postgresql
before_script:
  - cp config/database.example.json config/database.json
  - psql -c 'create database api_test;' -U postgres
  - yarn run migrate
script:
  - yarn run coverage
after_success:
  - cat ./coverage/lcov.info | coveralls
